### PR TITLE
Avoid space between the package name and version

### PR DESCRIPTION
**Pull request by danielbachhuber**
Not sure if it ever worked with the space but I get this error:

image

If I remove the space, it works fine.

### CODE REVIEW

**Comment by joejordanbrown** [comment]
My assumption was that was always for copying into packages.json and not for use with the require command?

**Comment by danielbachhuber** [comment]
@joejordanbrown Oh, interesting. `composer.json` would accept the package without a space too, but I hadn't considered that use case.

**Comment by bradyvercher** [comment]
I was wondering why there was a space when I saw how you were using it, but @joejordanbrown is correct that this was originally intended for copying into `composer.json`. The quotes wouldn't be necessary either for CLI and I imagined people would add constraints when using it that way. I suppose it's possible to add another field with the whole command if anyone would find that useful.

**Comment by danielbachhuber** [comment]
> I imagined people would add constraints when using it that way.

As a matter of fact, sometimes I want the constraint and other times I don't 😄

For when I don't, I end up copying out of the field, pasting, and then removing the excess.

> I suppose it's possible to add another field with the whole command if anyone would find that useful.

That'd work too.

**Comment by bradyvercher** [comment]
This should be good to go in version 0.7.

**Comment by danielbachhuber** [comment]
@bradyvercher Looks great, thanks!

**Pull request closed without merging**
